[package]
name = "emne-eksport"
version = "0.1.0"
authors = ["Henrik Hørlück Berg <henrik@horluck.no>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["env", "std", "color", "help", "usage", "error-context", "suggestions", "derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.24", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
openidconnect = "2.2"
log = "0.4"
env_logger = "0.9.3"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
fantoccini = "0.20.0-rc.3"
base64 = "0.13"
# must be equal to fantoccini's
webdriver = "0.46.0"
warp = "0.3.3"

