---
name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        driver: [chrome, firefox, edge]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          # not pre-installed
          - os: ubuntu-latest
            driver: firefox 

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start chrome
        run: chromedriver --port=4444 &
        shell: bash
        if: ${{ matrix.driver == 'chrome' }}

      - name: Start firefox
        run: geckodriver --port=4444 &
        shell: bash
        if: ${{ matrix.driver == 'firefox' }}

      - name: Start edge
        run: $EDGEWEBDRIVER/edgedriver --port=4444 &
        shell: bash
        if: ${{ matrix.driver == 'edge' }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
